#!/bin/bash -e
# SPDX-License-Identifier: GPL-2.0-only

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/envsetup.sh"
source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/cog.sh"

OUTPUT_ROOT=

function init() {
  OUTPUT_ROOT="${WORKSPACE_DIR}/out"

  # Kleaf's bazel wrapper only recognizes startup options in --<key>=<value> format.
  # --<key> <value> can not be recognized. Let's align with it.
  while (( $# > 0 )); do
    case "$1" in
      --output_root=*)
        OUTPUT_ROOT="$(realpath -s "${1#--output_root=}")"
        ;;
      -*)
        # Other startup options.
        ;;
      *)
        # Assume the first option not starting with `-` is the command.
        break
        ;;
    esac
    shift
  done

  readonly OUTPUT_ROOT
}

function import_device_bazelrc () {
  local search_dir="${WORKSPACE_DIR}/private/devices"
  local gen_device_bazelrc="${OUTPUT_ROOT}/bazel/bazelrc/device.bazelrc"

  local -a device_bazelrc_list
  readarray -t device_bazelrc_list < <(find "${search_dir}" -name device.bazelrc)

  mkdir -p "$(dirname "${gen_device_bazelrc}")"
  echo "# This file is auto-generated by tools/bazel." > "${gen_device_bazelrc}"

  local rc
  for rc in "${device_bazelrc_list[@]}"; do
    echo "import \"${rc/"${WORKSPACE_DIR}"/"%workspace%"}\"" >> "${gen_device_bazelrc}"
  done
  ln -snf "${gen_device_bazelrc}" "${WORKSPACE_DIR}/device.bazelrc"
}

function main() {
  init "$@"
  setup_cog_output_dir "${OUTPUT_ROOT}"
  import_device_bazelrc
  exec "${WORKSPACE_DIR}/build/kernel/kleaf/bazel.sh" "$@"
}

main "$@"
